[api]
host="0.0.0.0"
port=4040

[queue]
random_song_api="KAWA_RANDOM_SONG_URL"
nr="KAWA_NEXT_RANDOM_URL"
np="KAWA_NOW_PLAYING_URL"
fallback="/error.flac"

[radio]
port=8001
name="radio"
description=""
private=false


[[streams]]
mount="stream192.mp3"
codec="mp3"
container="mp3"
bitrate="v2"

[[streams]]
mount="stream128.aac"
container="aac"
codec="aac"
bitrate="vbr4"

[[streams]]
mount="stream64.ogg"
container="ogg"
codec="opus"
bitrate=64

[[streams]]
mount="stream128.ogg"
container="ogg"
codec="opus"
bitrate=128

[[streams]]
mount="stream256.ogg"
container="ogg"
codec="opus"
bitrate=256

[[streams]]
mount="stream.flac"
codec="flac"
container="flac"
bitdepth=16
block_size=4096
compression_level=7