<?php

define("SITE_HOSTNAME", "EXAMPLE_HOSTNAME");
define("DEFAULT_API_URL", "http://api:8011/api/");
define("DEFAULT_API_KEY", "EXAMPLE_DEFAULT_API_KEY");
define("LASTFM_API_KEY", "EXAMPLE_LASTFM_API_KEY");
define("POSTGRES_CONNECTION_STRING_MUSIC", "EXAMPLE_PSQL_STRING_MUSIC");
define("POSTGRES_CONNECTION_STRING_TORRENTS", "EXAMPLE_PSQL_STRING_TORRENTS");